//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EasySave.Resources {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EasySave.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Gérez et surveillez vos travaux de sauvegarde.
        /// </summary>
        internal static string AppSubtitle {
            get {
                return ResourceManager.GetString("AppSubtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à EASYSAVE.
        /// </summary>
        internal static string AppTitle {
            get {
                return ResourceManager.GetString("AppTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Veuillez entrer le dossier de destination.
        /// </summary>
        internal static string AskDestinationDirectory {
            get {
                return ResourceManager.GetString("AskDestinationDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Veuillez entrer le dossier source.
        /// </summary>
        internal static string AskSourceDirectory {
            get {
                return ResourceManager.GetString("AskSourceDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Sauvegarde bloquée.
        /// </summary>
        internal static string BackupBlocked {
            get {
                return ResourceManager.GetString("BackupBlocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Impossible de démarrer la sauvegarde : Le logiciel métier &apos;{0}&apos; est en cours d&apos;exécution.\n\nVeuillez fermer le logiciel métier et réessayer..
        /// </summary>
        internal static string BackupBlockedMessage {
            get {
                return ResourceManager.GetString("BackupBlockedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à ⚡ SAUVEGARDE EN COURS.
        /// </summary>
        internal static string BackupInProgress {
            get {
                return ResourceManager.GetString("BackupInProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Sauvegarde &apos;{0}&apos; démarrée !.
        /// </summary>
        internal static string BackupStarted {
            get {
                return ResourceManager.GetString("BackupStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à ⚙️ Type de sauvegarde.
        /// </summary>
        internal static string BackupTypeLabel {
            get {
                return ResourceManager.GetString("BackupTypeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Parcourir....
        /// </summary>
        internal static string Browse {
            get {
                return ResourceManager.GetString("Browse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Annuler.
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Consultez la console pour les logs multi-threading !.
        /// </summary>
        internal static string CheckConsole {
            get {
                return ResourceManager.GetString("CheckConsole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Complète.
        /// </summary>
        internal static string Complete {
            get {
                return ResourceManager.GetString("Complete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Créer le travail.
        /// </summary>
        internal static string CreateJob {
            get {
                return ResourceManager.GetString("CreateJob", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Configurer un nouveau travail de sauvegarde.
        /// </summary>
        internal static string CreateJobSubtitle {
            get {
                return ResourceManager.GetString("CreateJobSubtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 📋 CRÉER UN NOUVEAU TRAVAIL.
        /// </summary>
        internal static string CreateJobTitle {
            get {
                return ResourceManager.GetString("CreateJobTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Créer un travail.
        /// </summary>
        internal static string CreateNewJob {
            get {
                return ResourceManager.GetString("CreateNewJob", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 📄 Fichier actuel :.
        /// </summary>
        internal static string CurrentFile {
            get {
                return ResourceManager.GetString("CurrentFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 💾 Données :.
        /// </summary>
        internal static string Data {
            get {
                return ResourceManager.GetString("Data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à ✅ Décryptage réussi !\n\n⏱️ Temps : {0} ms.
        /// </summary>
        internal static string DecryptionSuccess {
            get {
                return ResourceManager.GetString("DecryptionSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 💾 Dossier de destination.
        /// </summary>
        internal static string DestinationFolderLabel {
            get {
                return ResourceManager.GetString("DestinationFolderLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Chemin de destination.
        /// </summary>
        internal static string DestinationPath {
            get {
                return ResourceManager.GetString("DestinationPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Différentielle.
        /// </summary>
        internal static string Differential {
            get {
                return ResourceManager.GetString("Differential", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à ❌ Échec du cryptage !\n\nErreur : {0}.
        /// </summary>
        internal static string EncryptionFailed {
            get {
                return ResourceManager.GetString("EncryptionFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à ✅ Cryptage réussi !\n\nFichier crypté : {0}\n\n⏱️ Temps : {1} ms.
        /// </summary>
        internal static string EncryptionSuccess {
            get {
                return ResourceManager.GetString("EncryptionSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 📁 Fichiers :.
        /// </summary>
        internal static string Files {
            get {
                return ResourceManager.GetString("Files", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Au revoir !.
        /// </summary>
        internal static string Goodbye {
            get {
                return ResourceManager.GetString("Goodbye", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Choix invalide. Veuillez réessayer..
        /// </summary>
        internal static string InvalidChoice {
            get {
                return ResourceManager.GetString("InvalidChoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Travail &apos;{0}&apos; créé avec succès !\n\nRemarque : Le travail sera persisté lors de l&apos;intégration avec la gestion des travaux de l&apos;équipe Console..
        /// </summary>
        internal static string JobCreatedSuccess {
            get {
                return ResourceManager.GetString("JobCreatedSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Nom du travail.
        /// </summary>
        internal static string JobName {
            get {
                return ResourceManager.GetString("JobName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 📝 Nom du travail.
        /// </summary>
        internal static string JobNameLabel {
            get {
                return ResourceManager.GetString("JobNameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Langue :.
        /// </summary>
        internal static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 1 - Creer un nouveau travail de sauvegard (Complete).
        /// </summary>
        internal static string MenuOption1 {
            get {
                return ResourceManager.GetString("MenuOption1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 2 - Creer un nouveau travail de sauvegarde (Differentiel).
        /// </summary>
        internal static string MenuOption2 {
            get {
                return ResourceManager.GetString("MenuOption2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 3 - Lancer un travail de sauvegarde.
        /// </summary>
        internal static string MenuOption3 {
            get {
                return ResourceManager.GetString("MenuOption3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 5 - Quitter.
        /// </summary>
        internal static string MenuOption4 {
            get {
                return ResourceManager.GetString("MenuOption4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 4 - Lancer plusieurs travaux de sauvegard.
        /// </summary>
        internal static string MenuOption5 {
            get {
                return ResourceManager.GetString("MenuOption5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Votre choix &gt; .
        /// </summary>
        internal static string MenuPrompt {
            get {
                return ResourceManager.GetString("MenuPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à ######################################################################################
        ///#                                                                                    #
        ///#   ########    ###      ####### ##    ##  #######    ###   ##        ##  ########   #
        ///#   ##         ## ##    ##        ##  ##  ##         ## ##   ##      ##   ##         #
        ///#   ######    ##   ##   ########   ####   ########  ##   ##   ##    ##    ########   #
        ///#   ##       #########         ##   ##          ## #########   ##  ##    [le reste de la chaîne a été tronqué]&quot;;.
        /// </summary>
        internal static string MenuTitle {
            get {
                return ResourceManager.GetString("MenuTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Aucun travail de sauvegarde disponible..
        /// </summary>
        internal static string NoJobAvailable {
            get {
                return ResourceManager.GetString("NoJobAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Aucun travail.
        /// </summary>
        internal static string NoJobs {
            get {
                return ResourceManager.GetString("NoJobs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Aucun travail de sauvegarde à exécuter.\n\nVeuillez d&apos;abord créer un travail en cliquant sur &apos;Créer un travail&apos;..
        /// </summary>
        internal static string NoJobsMessage {
            get {
                return ResourceManager.GetString("NoJobsMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Fichier original créé :\n{0}\n\nContenu : {1}.
        /// </summary>
        internal static string OriginalFileCreated {
            get {
                return ResourceManager.GetString("OriginalFileCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à ⏸️ Pause.
        /// </summary>
        internal static string Pause {
            get {
                return ResourceManager.GetString("Pause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Veuillez entrer un nom de travail..
        /// </summary>
        internal static string PleaseEnterJobName {
            get {
                return ResourceManager.GetString("PleaseEnterJobName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Veuillez sélectionner un dossier de destination..
        /// </summary>
        internal static string PleaseSelectDestination {
            get {
                return ResourceManager.GetString("PleaseSelectDestination", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Veuillez sélectionner un dossier source..
        /// </summary>
        internal static string PleaseSelectSource {
            get {
                return ResourceManager.GetString("PleaseSelectSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à ⏱️ Restant :.
        /// </summary>
        internal static string Remaining {
            get {
                return ResourceManager.GetString("Remaining", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Lancer la sélection.
        /// </summary>
        internal static string RunSelection {
            get {
                return ResourceManager.GetString("RunSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Sélectionnez le travail à lancer :.
        /// </summary>
        internal static string SelectJob {
            get {
                return ResourceManager.GetString("SelectJob", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Paramètres.
        /// </summary>
        internal static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Les dossiers source et destination ne peuvent pas être identiques..
        /// </summary>
        internal static string SourceDestinationSame {
            get {
                return ResourceManager.GetString("SourceDestinationSame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 📂 Dossier source.
        /// </summary>
        internal static string SourceFolderLabel {
            get {
                return ResourceManager.GetString("SourceFolderLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le dossier source n&apos;existe pas..
        /// </summary>
        internal static string SourceNotExist {
            get {
                return ResourceManager.GetString("SourceNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Chemin source.
        /// </summary>
        internal static string SourcePath {
            get {
                return ResourceManager.GetString("SourcePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à ⚡ Vitesse :.
        /// </summary>
        internal static string Speed {
            get {
                return ResourceManager.GetString("Speed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Status.
        /// </summary>
        internal static string State {
            get {
                return ResourceManager.GetString("State", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Succès.
        /// </summary>
        internal static string Success {
            get {
                return ResourceManager.GetString("Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Type.
        /// </summary>
        internal static string Type {
            get {
                return ResourceManager.GetString("Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Erreur de validation.
        /// </summary>
        internal static string ValidationError {
            get {
                return ResourceManager.GetString("ValidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à EasySave v2.0 - Tableau de bord.
        /// </summary>
        internal static string WindowTitle {
            get {
                return ResourceManager.GetString("WindowTitle", resourceCulture);
            }
        }
    }
}
